export const ACCESS_ITEMS: { key: string; label: string }[] = [
  { key: "zohoEmail",          label: "Zoho Email" },
  { key: "microsoftEmail",     label: "Microsoft Email" },
  { key: "microsoftOffice",    label: "Microsoft Office" },
  { key: "finfluxBmDashboard", label: "Finflux BM Dashboard" },
  { key: "mobiliteField",      label: "Mobilite Field" },
  { key: "mobiliteCredit",     label: "Mobilite Credit" },
  { key: "hoDashboard",        label: "HO Dashboard" },
  { key: "lightMoney",         label: "Light Money" },
  { key: "zohoProjects",       label: "Zoho Projects" },
  { key: "jira",               label: "Jira" },
  { key: "bitbucket",          label: "Bitbucket" },
  { key: "adobeAcrobat",       label: "Adobe Acrobat" },
  { key: "assetcuez",          label: "Assetcues" },
  { key: "vpn",                label: "VPN" },
  { key: "mailVault",          label: "MailVault" },
  { key: "acronisBackup",      label: "Acronis Backup" },
  { key: "exotel",             label: "Exotel" },
  { key: "godaddy",            label: "GoDaddy" },
  { key: "bluehost",           label: "Bluehost" },
  { key: "hostinger",          label: "Hostinger" },
  { key: "emailHosting",       label: "Email Hosting" },
  { key: "awsConsole",         label: "AWS Console" },
  { key: "msg91",              label: "MSG91" },
  { key: "dmsAlfresco",        label: "DMS / Alfresco" },
];
